// IMPORTANT!
// This file has been automatically generated,
// in order to update its content execute "pnpm run update"
import type { ESLint, Linter } from 'eslint';
import * as parser from 'svelte-eslint-parser';
let pluginObject: ESLint.Plugin | null = null;
export function setPluginObject(plugin: ESLint.Plugin): void {
	pluginObject = plugin;
}
const config: Linter.Config[] = [
	{
		name: 'svelte:base:setup-plugin',
		plugins: {
			get svelte(): ESLint.Plugin {
				return pluginObject!;
			}
		}
	},
	{
		name: 'svelte:base:setup-for-svelte',
		files: ['*.svelte', '**/*.svelte'],
		languageOptions: {
			parser
		},
		rules: {
			// ESLint core rules known to cause problems with `.svelte`.
			'no-inner-declarations': 'off', // The AST generated by svelte-eslint-parser will false positives in it rule because the root node of the script is not the `Program`.
			// "no-irregular-whitespace": "off",
			// Self assign is one of way to update reactive value in Svelte.
			'no-self-assign': 'off',

			// eslint-plugin-svelte rules
			'svelte/comment-directive': 'error',
			'svelte/system': 'error'
		},
		processor: 'svelte/svelte'
	}
];
export default config;
