// IMPORTANT!
// This file has been automatically generated,
// in order to update its content execute "pnpm run update"
export = {
	plugins: ['svelte'],
	overrides: [
		{
			files: ['*.svelte'],
			parser: require.resolve('svelte-eslint-parser'),
			rules: {
				// ESLint core rules known to cause problems with `.svelte`.
				'no-inner-declarations': 'off' as const, // The AST generated by svelte-eslint-parser will false positives in it rule because the root node of the script is not the `Program`.
				// "no-irregular-whitespace": "off" as const,
				// Self assign is one of way to update reactive value in Svelte.
				'no-self-assign': 'off' as const,

				// eslint-plugin-svelte rules
				'svelte/comment-directive': 'error' as const,
				'svelte/system': 'error' as const
			}
		}
	]
};
